version: 2
jobs:
  build:
    working_directory: ~/nugit/tube
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      SBT_VERSION: 0.13.17
      SBT_OPTS: -Xms3072M -Xmx3072M -Xss1M -XX:+CMSClassUnloadingEnabled
      COVERALLS_REPO_TOKEN: epxO4zHVNvU9gbIfnfgXsqYRNuyWhw5GZ
    docker:
    - image: circleci/openjdk:8-jdk-node
    steps:
    - checkout
    - run: git submodule sync --recursive
    - run: git submodule update --recursive --init
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: /opt/sbt/bin/sbt coverageOn clean test
    - run: /opt/sbt/bin/sbt coverageReport coveralls
    - run: mkdir -p $CIRCLE_ARTIFACTS/scala-2.11
    - run: mv target/scala-2.11/coverage-report  $CIRCLE_ARTIFACTS/scala-2.11/coverage-report
    - run: mv target/scala-2.11/scoverage-report $CIRCLE_ARTIFACTS/scala-2.11/scoverage-report
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
